CREATE TABLE genres (
   id UUID PRIMARY KEY,
   name VARCHAR(200) UNIQUE,
   slug VARCHAR(200) UNIQUE,  
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)